Improve guides
carbynestack/carbynestack.github.io pull request #22
Opened 2021-11-25 14:44 UTC by strieflin

2021-11-25 15:11 UTC, riedervi approved these changes
This is actually as intended. But maybe the numeration should be one (i.e. the second 1. should be a 4.)

2021-11-25 15:17 UTC, riedervi requested changes
I think, this change should be made at the page before, i.e. at "Setting up the clusters". If the two clusters are set up in the wrong directory, the whole setup must be done once again. So it might be convenient to clone the git repository into a desired repository as a first step. Then one can set up the clusters in this directory.

2021-11-25 15:21 UTC, strieflin commented
> This is actually as intended. But maybe the numeration should be one (i.e. the second 1. should be a 4.)

That's a markdown feature. Any sequence of arbitrary numbers, e.g. 1., 1., 1., will be converted into a sequence of consecutive numbers.

I recommend not to proof-read the sources but the generated site. See the README file for instructions on how to do this.

2021-11-25 15:26 UTC, strieflin commented
> I think, this change should be made at the page before, i.e. at "Setting up the clusters". If the two clusters are set up in the wrong directory, the whole setup must be done once again. So it might be convenient to clone the git repository into a desired repository as a first step. Then one can set up the clusters in this directory.

Actually, it doesn't matter what the current directory is, when you setup the kind clusters. There is no dependency whatsoever on a file or directory in that step. The only thing that matters is that you are in the right directory when performing the steps described in the "Stack Deployment" guide, because `helmfile` expects the `helmfile.d` directory in the working directory.

2021-11-25 15:34 UTC, riedervi commented
Thank you for these explanations. Then it's ok from my side

2021-11-26 05:33 UTC, sbckr submitted a review, later dismissed
LGTM

2021-11-26 08:04 UTC, grevend-bosch requested changes

2021-11-26 08:04 UTC, grevend-bosch commented on docs/getting-started/deployment.md
> +   and descend into to repository root directory using:
into & to?

2021-11-26 08:47 UTC, sbckr approved these changes
:+1:

2021-11-26 08:49 UTC, strieflin commented on docs/getting-started/deployment.md
> +   and descend into to repository root directory using:
Thx. Fixed that issue.

2021-11-26 08:50 UTC, merged