Adding instructions to setup cs with wsl2
carbynestack/carbynestack.github.io pull request #78
Opened 2023-02-02 15:20 UTC by adelSalah78

Adding instructions to setup cs with wsl2

2023-02-03 07:58 UTC, strieflin requested changes
Hi @adelSalah78, thank you very much for opening this PR. The content you want to have added, however, should not be part of the README of this repo but of the _content of the website_, which you can find in the `docs` folder. In addition, many of the steps you describe are already covered by https://carbynestack.io/getting-started/prerequisites/. You should only describe steps specific to WSL. Depending on how big the differences are it might be best to rewrite https://carbynestack.io/getting-started/prerequisites/ to contain WSL and Linux specific instructions. If the steps are the same and we only need a couple of steps to be done to get a Linux via WSL and can then continue with the steps for Linux already describe, then adding a new page with the WSL-specific setup steps might make more sense.

2023-02-03 12:38 UTC, adelSalah78 commented
> Hi @adelSalah78, thank you very much for opening this PR. The content you want to have added, however, should not be part of the README of this repo but of the _content of the website_, which you can find in the `docs` folder. In addition, many of the steps you describe are already covered by https://carbynestack.io/getting-started/prerequisites/. You should only describe steps specific to WSL. Depending on how big the differences are it might be best to rewrite https://carbynestack.io/getting-started/prerequisites/ to contain WSL and Linux specific instructions. If the steps are the same and we only need a couple of steps to be done to get a Linux via WSL and can then continue with the steps for Linux already describe, then adding a new page with the WSL-specific setup steps might make more sense.

Hi @strieflin , Kindly find the updates that I have made into the documentations of setting up CS with WSL2 on Windows.
Please let me know if there are any updates needed.

> Hi @adelSalah78, thank you very much for opening this PR. The content you want to have added, however, should not be part of the README of this repo but of the _content of the website_, which you can find in the `docs` folder. In addition, many of the steps you describe are already covered by https://carbynestack.io/getting-started/prerequisites/. You should only describe steps specific to WSL. Depending on how big the differences are it might be best to rewrite https://carbynestack.io/getting-started/prerequisites/ to contain WSL and Linux specific instructions. If the steps are the same and we only need a couple of steps to be done to get a Linux via WSL and can then continue with the steps for Linux already describe, then adding a new page with the WSL-specific setup steps might make more sense.

2023-02-13 14:42 UTC, strieflin commented
Not quite there yet @adelSalah78 😉:

1. Please check the PR regarding consistent  style, grammar, and spelling.
2. Please make sure that the guide doesn't repeat the steps described [here](https://carbynestack.io/getting-started/prerequisites/). I'd suggest to remove all duplicate steps from your PR.
3. The links to the other guides at the end are not necessary, as a link to the next page is rendered by `mkdocs` anyway.
4. Please add a step (new step 2) to the enumeration at the end of https://carbynestack.io/getting-started/ that links to your guide.

2023-02-13 14:43 UTC, strieflin requested changes

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +Carbyne Stack via WSL2 in windows.
**W**indows

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    WSL2 must be installed in your Windows machine.
*o*n

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    To install WSL2, run your Windows powershell and run this command
*P*owershell

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +Or you can refer to https://www.windowscentral.com/how-install-wsl2-windows-10 if more details are needed.
Don't use plain links as they reduce readability:

> Or you can refer to [this guide](https://www.windowscentral.com/how-install-wsl2-windows-10) if more details are needed.

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +### install Ubuntu-20.04 inside WSL2 and connect to it
**I**nstall

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +### install Ubuntu-20.04 inside WSL2 and connect to it
Use "Ubuntu 20.04" w/o the hyphen, please.

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    1. prevent creating the resolve.conf on startup
Always use capital letters at the beginning of sentences.

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    And add this text to wsl.conf file
Use

> And add this text to `wsl.conf` file

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    then press CTRL+X to save your file
Well, I think that is too much detail. People should know how to save in their editor 😀

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    And add this text to wsl.conf file
Please check that you adhere to this style for filenames throughout the whole file

2023-02-13 14:43 UTC, strieflin commented on docs/getting-started/prerequisites-wsl2.md
> +    ```shell
Add an empty line between text and code snippets. Make sure to adhere to this rule throughout the whole file.

2024-02-20 11:52 UTC, strieflin commented
Closed due to inactivity. Feel free to reopen when requested changes have been made.

2024-02-20 11:52 UTC, closed without merging